on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    name: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: npm install
      - name: Build Vitepress
        run: npm run build
